apiVersion: v1
kind: Secret
metadata:
  name: razvantiu-imagepull
  namespace: api
type:  kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAgICJ1c2VybmFtZSI6ICJyYXp2YW50aXUiLAogICAgICAgICJwYXNzd29yZCI6ICJkY2tyX3BhdF9zUnZiSlNwQ1Z5RUxnV0VHeVNMWWFOTFNmWGsiCiAgICAgIH0KICAgIH0KICB9